config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'news#index'

  get 'robots' => 'public#robots', format: :text
  get '/auth/:provider/callback', to: 'sessions#create'
  get "help", to: "static_pages#help"
  get "about", to: "static_pages#about"
  get "advert", to: "static_pages#advert"
  get "partners", to: "static_pages#partners"
  get "home", to: "static_pages#home"
  get "feed" => "news#feed", format: 'rss'
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: "users/confirmations", passwords: "users/passwords", :omniauth_callbacks => "users/omniauth_callbacks"}
  devise_scope :user do
    get "login", to: "users/sessions#new"
    get "signup", to: "users/registrations#new"
  end
  post "photos", to: "photos#create"
  resources :profiles
  resources :news
  resources :shoppingandmakeup
  resources :mvive_tv
  resources :exclusive
  resources :event
  resources :peopleandparty
  resources :moda
  resources :woman_fashion
  resources :men_fashion
  resources :fashionshow
  resources :krasota_ta_zdorovja
  resources :blog_khrystyna_kolyada
  resources :blog_olena_nazar
  resources :beauty_novunku
  resources :beauty_trend
  resources :kultura
  resources :lifestyle
  resources :travel


  get "my_profile", to: "profiles#my_profile"
  get "search", to: "profiles#search"
  get "feed", to: "profiles#index"

  resources :relationships, only: [:create, :destroy]
  resources :conversations, only: [:index, :show]
  resources :castings, only: [:index, :show, :new, :create]
  delete "castings/:id", to: "castings#destroy", as: :destroy_casting
  get "premium", to: "castings#premium"
  resources :users do
    resources :feedbacks
  end
  post "messages/:id", to: "messages#create", as: :messages
  post "add/:id", to: "conversations#add_conversation", as: :add
  post "comments/:id", to: "comments#create", as: :comments
  post "castings/select/:id", to: "castings#select_user", as: :select
  post "castings/unselect/:id", to: "castings#unselect_user", as: :unselect
end

app/models/casting.rb
class Casting < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  serialize :license
  validates :subject,  presence: true
  validates :price,  presence: true
  validates :country_code,  presence: true
  validates :city,  presence: true
  validates :task,  presence: true
  self.per_page = 7

  def country_name
    country = ISO3166::Country[country_code]
    country.translations[I18n.locale.to_s] || country.name
  end
end

app/controllers/castings_controller.rb
class CastingsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :premium]

  def index
    @castings = Casting.all.order('rating DESC')
    @castings = @castings.where("city LIKE ?", "%#{params[:city]}%") unless params[:city].blank?
    @castings = @castings.where("price LIKE ?", "%#{params[:price]}%") unless params[:price].blank?
    @castings = @castings.where("tag1 LIKE ?", "%#{params[:tag1]}%") unless params[:tag1].blank?
    @castings = @castings.where("tag2 LIKE ?", "%#{params[:tag2]}%") unless params[:tag2].blank?
    @castings = @castings.where("tag3 LIKE ?", "%#{params[:tag3]}%") unless params[:tag3].blank?
    @castings = @castings.paginate(page: params[:page], per_page: 5)
  end

  def new
    @casting = Casting.new
  end

  def create
    @casting = current_user.castings.build(casting_params)
    if @casting.save
      redirect_to casting_path(@casting)
    else
      redirect_to new_casting_path
    end
  end

  def show
    @casting = Casting.find(params[:id])
    @user = @casting.user
    @comments = @casting.comments
    @comment = Comment.new
  end

  def select_user
    @casting = Casting.find(params[:id])
    @casting.selected += (params[:usr] + "o")
    @casting.save
    redirect_to casting_path(@casting)
  end

  def unselect_user
    @casting = Casting.find(params[:id])
    x = @casting.selected.delete(params[:usr] + "o")
    @casting.selected = x
    @casting.save
    redirect_to casting_path(@casting)
  end

  def destroy
    @casting = Casting.find(params[:id])
    if current_user == @casting.user
    @casting.destroy
    end
    redirect_to castings_path(@castings)
  end

  def premium

  end


  private
  def casting_params
    params.require(:casting).permit(:rating, :subject, :price, :tag1, :tag2, :tag3, :country_code, :city,
                                    :task, :license => [])
  end
end

app/helpers/castings_helper.rb
module CastingsHelper
end

app/views/castings/index.html.erb
<% content_for(:title, 'Онлайн кастинги/фриланс | Найти фотографа, модель для фотосъемки')%>
<% content_for(:description, "Нужна модель или фотограф для фотосъемки? Создавайте онлайн-кастинг и выбирайте из участников, которые подали заявку.") %>
<% content_for(:keywords, 'онлайн-кастинг, makeup, фотограф, модель, найти, визажист, макияж')%>

<%= render 'shared/menu' %>
<div class="global-scope">
  <div style="padding-left: 230px" class="settings-scope">
    <h2>Онлайн кастинги</h2>
    <!--Link to form-->
    <div class="casting-btn-wrapper">
      <%= link_to content_tag(:span, '<i class="fa fa-plus"></i>'.html_safe + "Создать кастинг",  class: "button-casting-form"), new_casting_path %>
      <%= link_to 'Премиум кастинги от MVive'.html_safe, premium_path, class: "button-casting-form-premium", target: "_self" %>
    </div>

    <%= form_tag castings_path, :method => 'get', id: "casting-search" do%>
        <div class="casting-filter-forms">
          <h4>Фильтр</h4>
          <p>Город, Цена, таг1, таг2, таг3</p>
          <%= text_field_tag :city, nil, placeholder: 'test1', class: 'castings-filter-tag' %>

          <%= text_field_tag :price, nil, class: 'castings-filter-tag' %>

          <%= text_field_tag :tag1, nil, class: 'castings-filter-tag' %>

          <%= text_field_tag :tag2, nil, class: 'castings-filter-tag' %>

          <%= text_field_tag :tag3, nil, class: 'castings-filter-tag' %>
          <input class="casting-btn-filter" type="submit" value="Поиск">
        </div>
    <% end %>
    <% @castings.each do|c| %>
        <div class="casting-card-view">
          <div class="casting-card-title">
            <h3><%= c.subject %></h3>
            <div class="casting-info">
              <i class="fa fa-map-marker"></i>
              <p><%= "#{c.country_name} #{c.city}" %></p>
              <i class="fa fa-clock-o" style="margin-left: 5px;"></i>
              <p><%= c.created_at.to_date.to_s(:db) %></p>
            </div>
            <div class="title-tag price-tag">
              <p><%= c.price %></p><i class="fa fa-money"></i>
            </div>

            <% unless c.license.blank? %>
                <% c.license.each do |lic|%>
                    <div class="title-tag">
                      <p><%= lic %></p>
                    </div>
                <%end%>
            <%end%>

            <% unless c.tag1.blank? %>
                <div class="title-tag">
                  <p><%= c.tag1 %></p>
                </div>
            <% end %>

            <% unless c.tag2.blank? %>
                <div class="title-tag">
                  <p><%= c.tag2 %></p>
                </div>
            <% end %>

            <% unless c.tag3.blank? %>
                <div class="title-tag">
                  <p><%= c.tag3 %></p>
                </div>
            <% end %>

          </div>
          <div class="casting-card-content">
            <p><%= c.task %></p>
            <%= link_to content_tag(:button, "Посмотреть", class: "show-casting-single"), casting_path(c), target: "_self" %>
          </div>
        </div>
    <% end %>

    <div class="google-ads-castings-main">
      <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
      <!-- mv-castings-main -->
      <ins class="adsbygoogle"
           style="display:inline-block;width:728px;height:90px"
           data-ad-client="ca-pub-3562964519569523"
           data-ad-slot="4170794094"></ins>
      <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
      </script>
    </div>

    <div class="casting-next-back-btns">
      <%= will_paginate @casting, previous_label: "Назад", next_label: "Вперед" %>
    </div>
    <%=render "shared/footer" %>
  </div>
</div>

app/views/castings/new.html.erb
<% content_for(:title, 'Новый кастинг | Freelance')%>

<%= render 'shared/menu' %>
<div class="global-scope">
			<div style="padding-left: 230px" class="settings-scope">
				<h2 class="divider">Создание кастинга</h2>
				<%= form_for @casting, html:{class: "profile-settings-private"} do |f|%>
					<label class="required-star">Заголовок кастинга</label>
					<div class="setter-line">
						<%= f.text_field :subject, required: true %>
					</div>
					<label class="required-star">Цена</label>
					<div class="setter-line">
						<%= f.number_field :price, required: true, min: "0"%>
					</div>
					<label>Тег 1 (необязательно)</label>
					<div class="setter-line">
						<%= f.text_field :tag1 %>
					</div>
					<label>Тег 2 (необязательно)</label>
					<div class="setter-line">
						<%= f.text_field :tag2 %>
					</div>
					<label>Тег 3 (необязательно)</label>
					<div class="setter-line">
						<%= f.text_field :tag3 %>
					</div>
					<label for="set-country" class="required-star">Страна кастинга</label>
					<div class="setter-line">
						<div class="select-plus"></div>
						<%= f.country_select :country_code,  {include_blank:'Выберите страну из списка', only: ["UA", "RU", "BY"], selected: current_user.country_code}, id: "set-country", required: true %>
					</div>
					<label class="required-star">Город кастинга</label>
					<div class="setter-line">
						<%= f.text_field :city, required: true %>
					</div>
					<label class="required-star">Техническое задание</label>
					<div class="setter-line setter-area">
						<%= f.text_area :task, required: true %>
					</div>
					<div class="multiselect-list" id="multiselect-license-list">
							<div class="selected-items">
								<span id="selected-skills-photo">Выберите лицензию</span>
							</div>
							<label><%= f.check_box :license, {:multiple => true}, "TFP", nil %>TFP</label>
							<label><%= f.check_box :license, {:multiple => true}, "TFCD", nil %>TFCD</label>
							<label><%= f.check_box :license, {:multiple => true}, "Коммерческая съемка", nil %>Коммерческая съемка</label>
						</div>
					<div class="setter-line setter-line-button">
						<%= f.submit "Создать" %>
					</div>
				<% end %>
        <%=render "shared/footer" %>
			</div>
		</div>

app/views/castings/premium.html.erb
<% content_for(:title, 'Премиум кастинг от MVive | Freelance')%>

<%= render 'shared/menu' %>
<div class="global-scope">
  <div style="padding-left: 270px" class="settings-scope">
    <h2>Премиум кастинг от M'Vive</h2>
    <div class="ab-pr-cast">
      <img src="https://s3.amazonaws.com/mvive-news-images/images-news/12803003_612974018841025_2020559460027736913_n.jpg" width="890" style="padding: 15px 0 15px 0">
      <h3>О конкурсе:</h3>
      <p>На честь открытия новой Online-платформы для фотографов, моделей и модельеров спешим сообщить о запуске конкурса для фото-моделей на наши рекламные стоки ! Что бы принять участие Вам достаточно подять заявку и иметь учетную запись на сайте с несколько фотографий (Полный рост, профиль).</p>
      <h4>Прием заявок ЗАКРЫТ !<br><br>Регистрация и Вход через Facebook на данный момент не активна! Если у Вас возникли проблемы, пишите на email: info.mvive@gmail.com</h4>
      <div class="ggl-forms-block">
        <a href="https://docs.google.com/forms/d/e/1FAIpQLSduFTrxBnGSgYh_5_nsKI4_EVUEQ7dONSSzg3-RghF_wRqWXw/viewform"><p class="btn-for-forms">Принять участие</p></a>
      </div>

      <!--
      <h3>Спонсоры конкурса:</h3>
      <div class="info-partners">
        <div class="info-partner-block">
          <%= image_tag "big-logo.PNG", class: "info-part-logos" %>
          <h4 class="info-part-main-h4">M'Vive</h4>
          <p>Freelance платформа для фотографов и моделей</p>
        </div>
        <div class="info-partner-block">
          <%= image_tag "big-logo.PNG", class: "info-part-logos" %>
          <h4 class="info-part-main-h4">M'Vive</h4>
          <p>Freelance платформа для фотографов и моделей</p>
        </div>
        <h3>Партнеры:</h3>
        <div class="info-partner-block">
          <%= image_tag "big-logo.PNG", class: "info-part-logos" %>
          <h4 class="info-part-main-h4">M'Vive</h4>
          <p>Freelance платформа для фотографов и моделей</p>
        </div>
        <div class="info-partner-block">
          <%= image_tag "big-logo.PNG", class: "info-part-logos" %>
          <h4 class="info-part-main-h4">M'Vive</h4>
          <p>Freelance платформа для фотографов и моделей</p>
        </div>
        -->

        <div class="google-ads-info-partners">
          <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
          <!-- info-partners -->
          <ins class="adsbygoogle"
               style="display:inline-block;width:728px;height:90px"
               data-ad-client="ca-pub-3562964519569523"
               data-ad-slot="6644105690"></ins>
          <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
          </script>
        </div>
      </div>
        <h3 class="social-call">Мы в социальных сетях</h3>
        <div class="social-footer">
          <ul>
            <li><a href="https://vk.com/mvivenet"><i class="fa fa-vk"></i></a></li>
            <li><a href="https://www.facebook.com/mvivenet"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/castings/show.html.erb
<% content_for(:title, @casting.subject)%>
<% content_for(:description, @casting.task) %>
<% content_for(:keywords, @casting.tag1) %>

<%= render 'shared/menu' %>
<div class="global-scope">
  <div style="padding-left: 270px" class="settings-scope">
    <div class="overlay"></div>
    <%= form_for @comment, url: comments_path(@casting), method: :post, html: {class: "reg-scale add-comment-casting"} do |f|%>
        <div class="input-casting-line">
          <%= f.text_area :body, style: "height: 130px;", placeholder: "Введите ваш комментарий...", maxlength: "180", required: true%>
        </div>
        <div class="input-casting-line">
          <%= f.submit "Подать заявку" %>
        </div>
        <p id="cancel">Отмена</p>
    <% end %>
    <h2><%= @casting.subject %></h2>
    <!--Link to form-->

    <div class="casting-card-view">
      <div class="casting-card-title single-card-title">
        <div class="casting-single-author">
          <div class="profile-photo" style="background-image: url(<%= @user.avatar_url %>);">
          </div>
          <div class="casting-name">
            <h3><%="#{@user.name} #{@user.surname}" %></h3>
            <div class="casting-name-wrap">
              <p><%= @user.ruType %></p>
              <i class="fa fa-star"></i><p><%= @rating %></p>
            </div>
          </div>
          <% if current_user == @casting.user %>
          <div class="casting-destroy">
            <%= link_to '<p class="cast-dest-p">Удалить кастинг</p>'.html_safe, destroy_casting_path(@casting), data: {:confirm => 'Вы уверены?'}, :method => :delete %>
          </div>
              <% end %>
        </div>
        <div class="casting-info">
          <i class="fa fa-map-marker"></i>
          <p><%= "#{@casting.country_name} #{@casting.city}" %></p>
          <i class="fa fa-clock-o" style="margin-left: 5px;"></i>
          <p><%= @casting.created_at.to_date.to_s(:db) %></p>
        </div>
        <div class="title-tag price-tag">
          <p><%= @casting.price %></p><i class="fa fa-money"></i>
        </div>

        <% unless @casting.license.blank? %>
            <% @casting.license.each do |lic|%>
                <div class="title-tag">
                  <p><%= lic %></p>
                </div>
            <%end%>
        <%end%>

        <% unless @casting.tag1.blank? %>
            <div class="title-tag">
              <p><%= @casting.tag1 %></p>
            </div>
        <% end %>

        <% unless @casting.tag2.blank? %>
            <div class="title-tag">
              <p><%= @casting.tag2 %></p>
            </div>
        <% end %>

        <% unless @casting.tag3.blank? %>
            <div class="title-tag">
              <p><%= @casting.tag3 %></p>
            </div>
        <% end %>

      </div>
      <div class="casting-card-content single-card-content">
        <p><%= @casting.task %></p>
        <% if current_user %>
        <% unless current_user == @casting.user%>
            <button class="show-casting-single" style="display: block; margin-left: auto;margin-right: auto;">Подать заявку</button>
        <% end %>
        <% end %>
      </div>
    </div>

    <h2 class="divider">Участники</h2>
    <div class="casting-comments">
      <% check = (current_user == @casting.user)%>
      <% @comments.each do |c|%>
          <% if check2 = @casting.selected.include?(c.user_id.to_s) %>
              <div class="user-casting-comment current-user-cast">
          <% else %>
              <div class="user-casting-comment">
          <% end %>
          <div class="profile-photo" style="background-image: url(<%= c.user.avatar_url %>);"></div>
          <div class="casting-comment-wrap">
            <h3><%= "#{c.user.name} #{c.user.surname}" %></h3>
            <p><%= c.created_at.to_date.to_s(:db) %></p>
            <p><%= c.body %></p>
          </div>
          <% if check %>
              <% if check2 %>
                  <%= form_tag unselect_path(@casting) do%>
                      <%= hidden_field_tag :usr, c.user_id.to_s%>
                      <button class="show-casting-single1" style="display: block; margin: 25px auto 15px;">Удалить исполнителя</button>
                  <% end %>
              <% else %>
                  <%= form_tag select_path(@casting) do%>
                      <%= hidden_field_tag :usr, c.user_id.to_s%>
                      <button class="show-casting-single1" style="display: block; margin: 25px auto 15px;">Добавить исполнителя</button>
                  <% end %>
              <% end %>
          <% end %>
          </div>
      <% end %>
      </div>

      <div class="google-ads-castings-main">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- mv-casting-single -->
        <ins class="adsbygoogle"
             style="display:block"
             data-ad-client="ca-pub-3562964519569523"
             data-ad-slot="3313374896"
             data-ad-format="auto"></ins>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      </div>

    </div>
  </div>
<%=render "shared/footer" %>