config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'news#index'

  get 'robots' => 'public#robots', format: :text
  get '/auth/:provider/callback', to: 'sessions#create'
  get "help", to: "static_pages#help"
  get "about", to: "static_pages#about"
  get "advert", to: "static_pages#advert"
  get "partners", to: "static_pages#partners"
  get "home", to: "static_pages#home"
  get "feed" => "news#feed", format: 'rss'
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: "users/confirmations", passwords: "users/passwords", :omniauth_callbacks => "users/omniauth_callbacks"}
  devise_scope :user do
    get "login", to: "users/sessions#new"
    get "signup", to: "users/registrations#new"
  end
  post "photos", to: "photos#create"
  resources :profiles
  resources :news
  resources :shoppingandmakeup
  resources :mvive_tv
  resources :exclusive
  resources :event
  resources :peopleandparty
  resources :moda
  resources :woman_fashion
  resources :men_fashion
  resources :fashionshow
  resources :krasota_ta_zdorovja
  resources :blog_khrystyna_kolyada
  resources :blog_olena_nazar
  resources :beauty_novunku
  resources :beauty_trend
  resources :kultura
  resources :lifestyle
  resources :travel


  get "my_profile", to: "profiles#my_profile"
  get "search", to: "profiles#search"
  get "feed", to: "profiles#index"

  resources :relationships, only: [:create, :destroy]
  resources :conversations, only: [:index, :show]
  resources :castings, only: [:index, :show, :new, :create]
  delete "castings/:id", to: "castings#destroy", as: :destroy_casting
  get "premium", to: "castings#premium"
  resources :users do
    resources :feedbacks
  end
  post "messages/:id", to: "messages#create", as: :messages
  post "add/:id", to: "conversations#add_conversation", as: :add
  post "comments/:id", to: "comments#create", as: :comments
  post "castings/select/:id", to: "castings#select_user", as: :select
  post "castings/unselect/:id", to: "castings#unselect_user", as: :unselect
end

app/models/krasota_ta_zdorovja.rb
class KrasotaTaZdorovja < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user

  friendly_id :name, use: :slugged
end

app/controllers/krasota_ta_zdorovja_controller.rb
class KrasotaTaZdorovjaController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def index
    @krasota_ta_zdorovja = KrasotaTaZdorovja.all
    @krasota_ta_zdorovja = KrasotaTaZdorovja.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
  end

  def feed
    @krasota_ta_zdorovja = KrasotaTaZdorovja.all
    respond_to do |format|
      format.rss { render :layout => false }
    end
  end

  def show
    @krasota_ta_zdorovja = KrasotaTaZdorovja.friendly.find(params[:id])
  end

  def create
    if(current_user.is_admin?)
      @krasota_ta_zdorovja = current_user.krasota_ta_zdorovja.build(krasota_ta_zdorovja_params)
      @krasota_ta_zdorovja.save
    else
      redirect_to news_index_path
    end
  end

  private
  def krasota_ta_zdorovja_params
    params.require(:krasota_ta_zdorovja).permit(:name, :short, :body, :body2, :body3, :body4, :body5, :body6, :news_day, :news_month, :image, :image2, :image3, :image4, :image5, :image6)
  end
end

app/views/krasota_ta_zdorovja/index.html.erb
<% content_for(:title, "Красота та Здоров'я")%>
<% content_for(:description, "Останні новинки в б'юті індустрії, кращі СПА та салони краси. Де купувати дизайнерський одяг.") %>
<% content_for(:keywords, "красота, стиль, шопінг, спа")%>


<div class="global-scope">
  <div class="settings-scope" style="padding-top: 0;">
    <div class="up-logo-main">
      <%= image_tag "mvive-tv-white-small.png", alt: "MVive Fashion Channel", class: "up-logo" %>
    </div>
    <%= render "shared/main_news_navbar" %>
    <%= render "shared/news_slider_navbar" %>
    <h2 style="padding-top: 60px;">Останні оновлення</h2>
    <div class="news-feed">

      <% @krasota_ta_zdorovja.each do |krasota_ta_zdorovja| %>
          <div class="news-container">

            <h1><a href="<%= krasota_ta_zdorovja_path(krasota_ta_zdorovja) %>"><span class="headline-word"><%= krasota_ta_zdorovja.name %></span></a></h1>

            <a href="<%= krasota_ta_zdorovja_path(krasota_ta_zdorovja) %>" target="_self">
              <div class="news-photo" style="background-image: url(<%= krasota_ta_zdorovja.image %>);" >
                <div class="news-date-block">
                  <p class="news-date-day"><%= krasota_ta_zdorovja.news_day %></p>
                  <p class="news-date-month"><%= krasota_ta_zdorovja.news_month %></p>
                </div>
              </div>
            </a>

            <div class="news-content">
              <p><%= krasota_ta_zdorovja.short %></p>
            </div>

          </div>
      <% end %>
      <div class="google-ads-news-main">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- mv-news-main -->
        <ins class="adsbygoogle"
             style="display:inline-block;width:728px;height:90px"
             data-ad-client="ca-pub-3562964519569523"
             data-ad-slot="1356928495"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      </div>
    </div>

    <div class="casting-next-back-btns">
      <%= will_paginate @krasota_ta_zdorovja, previous_label: "Назад", next_label: "Вперед" %>
    </div>
  </div>
</div>
</div>
<%= render 'shared/footer' %>
<%= render 'shared/popup_facebook' %>
<div id='admixer_53fb9a119de44b9781dae1268142a911_zone_14307_sect_4206_site_3736'></div> <script type='text/javascript'> admixerML.fn.push(function() { admixerML.display('admixer_53fb9a119de44b9781dae1268142a911_zone_14307_sect_4206_site_3736'); }); </script>
<div class="admixer-mobile"><div id='admixer_b8ba839213ef46f4bb92b37158d0c2af_zone_14308_sect_4206_site_3736'></div> <script type='text/javascript'> admixerML.fn.push(function() { admixerML.display('admixer_b8ba839213ef46f4bb92b37158d0c2af_zone_14308_sect_4206_site_3736'); }); </script></div>

app/views/krasota_ta_zdorovja/show.html.erb
<% content_for(:title, @krasota_ta_zdorovja.name) %>
<% content_for(:description, @krasota_ta_zdorovja.body) %>
<% content_for(:og_title, @krasota_ta_zdorovja.name)%>
<% content_for(:og_description, @krasota_ta_zdorovja.body)%>
<% content_for(:og_image, @krasota_ta_zdorovja.image)%>


<div class="global-scope" xmlns="http://www.w3.org/1999/html">
  <div class="settings-scope">
    <div class="up-logo-main">
      <%= image_tag "mvive-tv-white-small.png", alt: "MVive Fashion Channel", class: "up-logo" %>
    </div>
    <%= render "shared/main_news_navbar" %>
    <div class="single-news-photo parallax-window" data-parallax="scroll" data-image-src="<%= @krasota_ta_zdorovja.image %>">
      <div class="single-news-main-text">
        <h1><%= @krasota_ta_zdorovja.name %></h1>
      </div>
    </div>
    <div class="back-btn">
      <i style="padding-left: 30px" class="fa fa-arrow-left fa-2x" aria-hidden="true"></i>
      <%= link_to "Вернутись", :back, class:"news-back-btn" %>
    </div>
    <p class="single-news-content"><%= @krasota_ta_zdorovja.body %></p>
    <div class="news-content-img">
      <img class="nci-img" src="<%= @krasota_ta_zdorovja.image2 %>">
    </div>
    <p class="single-news-content"><%= @krasota_ta_zdorovja.body2 %></p>
    <div class="news-content-img">
      <img class="nci-img" src="<%= @krasota_ta_zdorovja.image3 %>">
    </div>
    <p class="single-news-content"><%= @krasota_ta_zdorovja.body3 %></p>
    <div class="news-content-img">
      <img class="nci-img" src="<%= @krasota_ta_zdorovja.image4 %>">
    </div>
    <p class="single-news-content"><%= @krasota_ta_zdorovja.body4 %></p>
    <div class="news-content-img">
      <img class="nci-img" src="<%= @krasota_ta_zdorovja.image5 %>">
    </div>
    <p class="single-news-content"><%= @krasota_ta_zdorovja.body5 %></p>
    <div class="news-content-img">
      <img class="nci-img" src="<%= @krasota_ta_zdorovja.image6 %>">
    </div>
    <p class="single-news-content"><%= @krasota_ta_zdorovja.body6 %></p>

    <!-- <h2>Смотрите также:</h2>
    <div class="look-more-block">
      <a href="http://www.mvive.net/news/49" class="lm-block-a" target="_self">
        <div class="lm-block-single">
          <img src="https://s3.amazonaws.com/mvive-news-images/images-news/19-okt-1.jpeg" class="lm-block-img">
          <p class="lm-block-p">Покрова: как создавался этно-проект от Vogue.ua и другое</p>
        </div>
      </a>

      <a href="http://www.mvive.net/news/51" class="lm-block-a" target="_self">
        <div class="lm-block-single">
          <img src="https://s3.amazonaws.com/mvive-news-images/images-news/24-okt-1.jpeg" class="lm-block-img">
          <p class="lm-block-p">Dolce&Gabbana: сыновья звезд снялись в рекламе</p>
        </div>
      </a>
    </div> -->

    <div class="google-ads-news-single">
      <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
      <!-- mv-news-single -->
      <ins class="adsbygoogle"
           style="display:inline-block;width:728px;height:90px"
           data-ad-client="ca-pub-3562964519569523"
           data-ad-slot="8740594493"></ins>
      <script>
          (adsbygoogle = window.adsbygoogle || []).push({});
      </script>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>
<!-- Share Buttons -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-57ce7fb5ff12a99b"></script>
<div id='admixer_53fb9a119de44b9781dae1268142a911_zone_14307_sect_4206_site_3736'></div> <script type='text/javascript'> admixerML.fn.push(function() { admixerML.display('admixer_53fb9a119de44b9781dae1268142a911_zone_14307_sect_4206_site_3736'); }); </script>
<div class="admixer-mobile"><div id='admixer_b8ba839213ef46f4bb92b37158d0c2af_zone_14308_sect_4206_site_3736'></div> <script type='text/javascript'> admixerML.fn.push(function() { admixerML.display('admixer_b8ba839213ef46f4bb92b37158d0c2af_zone_14308_sect_4206_site_3736'); }); </script></div>