config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'news#index'

  get 'robots' => 'public#robots', format: :text
  get '/auth/:provider/callback', to: 'sessions#create'
  get "help", to: "static_pages#help"
  get "about", to: "static_pages#about"
  get "advert", to: "static_pages#advert"
  get "partners", to: "static_pages#partners"
  get "home", to: "static_pages#home"
  get "feed" => "news#feed", format: 'rss'
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: "users/confirmations", passwords: "users/passwords", :omniauth_callbacks => "users/omniauth_callbacks"}
  devise_scope :user do
    get "login", to: "users/sessions#new"
    get "signup", to: "users/registrations#new"
  end
  post "photos", to: "photos#create"
  resources :profiles
  resources :news
  resources :shoppingandmakeup
  resources :mvive_tv
  resources :exclusive
  resources :event
  resources :peopleandparty
  resources :moda
  resources :woman_fashion
  resources :men_fashion
  resources :fashionshow
  resources :krasota_ta_zdorovja
  resources :blog_khrystyna_kolyada
  resources :blog_olena_nazar
  resources :beauty_novunku
  resources :beauty_trend
  resources :kultura
  resources :lifestyle
  resources :travel


  get "my_profile", to: "profiles#my_profile"
  get "search", to: "profiles#search"
  get "feed", to: "profiles#index"

  resources :relationships, only: [:create, :destroy]
  resources :conversations, only: [:index, :show]
  resources :castings, only: [:index, :show, :new, :create]
  delete "castings/:id", to: "castings#destroy", as: :destroy_casting
  get "premium", to: "castings#premium"
  resources :users do
    resources :feedbacks
  end
  post "messages/:id", to: "messages#create", as: :messages
  post "add/:id", to: "conversations#add_conversation", as: :add
  post "comments/:id", to: "comments#create", as: :comments
  post "castings/select/:id", to: "castings#select_user", as: :select
  post "castings/unselect/:id", to: "castings#unselect_user", as: :unselect
end

app/models/beauty_trend.rb
class BeautyTrend < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user

  friendly_id :name, use: :slugged
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user

  friendly_id :name, use: :slugged
end

app/models/casting.rb
class Casting < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  serialize :license
  validates :subject,  presence: true
  validates :price,  presence: true
  validates :country_code,  presence: true
  validates :city,  presence: true
  validates :task,  presence: true
  self.per_page = 7

  def country_name
    country = ISO3166::Country[country_code]
    country.translations[I18n.locale.to_s] || country.name
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :casting
  validates :body,  presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user

  friendly_id :name, use: :slugged
end

app/models/exclusive.rb
class Exclusive < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user

  friendly_id :name, use: :slugged
end

app/models/fashionshow.rb
class Fashionshow < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user

  friendly_id :name, use: :slugged
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :user
  validates :body,  presence: true
end

app/models/kultura.rb
class Kultura < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user

  friendly_id :name, use: :slugged
end

app/models/lifestyle.rb
class Lifestyle < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user

  friendly_id :name, use: :slugged
end

app/models/men_fashion.rb
class MenFashion < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user

  friendly_id :name, use: :slugged
end

app/models/moda.rb
class Moda < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user

  friendly_id :name, use: :slugged
end

app/models/mvive_tv.rb
class MviveTv < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user

  friendly_id :name, use: :slugged
end

app/models/news.rb
class News < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user

  friendly_id :name, use: :slugged
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_many :votes
  belongs_to :user
  validates :image, file_size: { less_than: 2.megabytes }
  mount_uploader :image, PhotoUploader
  
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
  
end

app/models/travel.rb
class Travel < ActiveRecord::Base
  extend FriendlyId

  belongs_to :user

  friendly_id :name, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_LOGIN_REGEX = /\A[A-z0-9\-_]+\z/
  validates :login,  presence: true, uniqueness: true , length: { maximum: 25, minimum: 6 }, format: {with: VALID_LOGIN_REGEX}
  validates :name,  presence: true, on: :update
  validates :surname,  presence: true, on: :update
  validates :city,  presence: true, on: :update
  validates :avatar, file_size: { less_than: 2.megabytes }
  validates :cover, file_size: { less_than: 2.megabytes }
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :timeoutable,
         :confirmable,
         :omniauthable, :omniauth_providers => [:facebook]      
  has_one :model_profile, dependent: :destroy
  has_one :designer_profile, dependent: :destroy
  has_one :photographer_profile, dependent: :destroy
  has_one :stylist_profile, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id", class_name:  "Relationship", dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  has_many :castings, :dependent => :destroy
  has_many :comments
  has_many :feedbacks

  has_many :news
  has_many :fashionandmakeup
  has_many :fashionshow
  has_many :shoppingandmakeup
  has_many :exclusive
  has_many :event
  has_many :moda
  has_many :woman_fashion
  mount_uploader :avatar, AvatarUploader
  mount_uploader :cover, CoverUploader
  acts_as_messageable
  
  def uname()
    "#{name} #{surname}"
  end
  
  def mailboxer_email(object)
    email
  end
  
  def age
     now = Time.now.utc.to_date
    now.year - birthday.year - ((now.month > birthday.month || (now.month == birthday.month && now.day >= birthday.day)) ? 0 : 1)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end
  
  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end
  
   def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy!
  end
  
  def voted?(some_photo)
    votes.find_by(photo_id: some_photo.id)
  end
  
  def like!(some_photo)
    votes.create!(photo_id: some_photo.id)
  end
  
  def unlike!(some_photo)
    votes.find_by(photo_id: some_photo.id).destroy!
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
    end
  end

  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
  def profile
    case type
    when "Photographer"
      photographer_profile
    when "Model"
      model_profile
    when "Designer"
      designer_profile
      when "Stylist"
        stylist_profile
    end
  end
  
  def ruType
    case type
    when "Photographer"
      "Фотограф"
    when "Model"
      "Модель"
    when "Designer"
      "Модельер"
      when "Stylist"
        "Стилист"
    end
  end
  
   def country_name
    country = ISO3166::Country[country_code]
    country.translations[I18n.locale.to_s] || country.name
   end

    def is_admin?
      admin == true
    end

   private
    def self.inheritance_column
      nil
    end
    
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/shared/_content_beautytrend.html.erb
<div class="row">
  <div class="col-lg-8 col-md-8 col-sm-8">
    <div class="left_content">

      <div class="single_moda_content">
        <h2><span>Бюті Тренд</span></h2>
        <div class="single_moda_content_left">
          <ul class="moda_catgnav">
            <li>
              <% @beauty_trend.each do |beauty_trend| %>
                  <figure class="bsbig_fig  wow fadeInDown"> <a class="featured_img" href="<%= beauty_trend_path(beauty_trend) %>"> <img src="<%= beauty_trend.image %>"><span class="overlay2"></span> </a>
                    <figcaption> <h1 style="font-size: 23px"><a href="<%= beauty_trend_path(beauty_trend) %>"><%= beauty_trend.name %></a></h1> </figcaption>
                    <p style="border-bottom: 1px solid #000000;"><%= beauty_trend.short %></p>
                  </figure>
              <% end %>
            </li>
          </ul>
        </div>

      </div>
    </div>
  </div>
  <div class="col-lg-4 col-md-4 col-sm-4">
    <aside class="right_content">
      <div class="single_sidebar">
        <h2><span>Популярні новини</span></h2>
        <ul class="spost_nav">
          <li>
            <div class="media wow fadeInDown"> <a href="http://mvive.net/news/anna_october_resort_2017_leto_blizko" class="media-left"><img src="https://s3.amazonaws.com/mvive-news-images/images-news/27-noya-2.jpeg" alt="Anna October Resort 2017"></a>
              <div class="media-body"> <a href="http://mvive.net/news/anna_october_resort_2017_leto_blizko" class="catg_title">Anna October Resort 2017: лето близко</a> </div>
            </div>
          </li>
          <li>
            <div class="media wow fadeInDown"> <a href="http://mvive.net/news/grammy-2017-epatagni-naryadu-ceremonii" class="media-left"><img src="https://s3.amazonaws.com/mvive-news-images/images-news/13-feb2-1.jpg" alt="Grammy 2017"></a>
              <div class="media-body"> <a href="http://mvive.net/news/grammy-2017-epatagni-naryadu-ceremonii" class="catg_title">Grammy 2017: епатажні наряди церемонії</a> </div>
            </div>
          </li>
          <li>
            <div class="media wow fadeInDown"> <a href="http://mvive.net/news/zhukova-jewelry-nova-kolekciya-love-is" class="media-left"><img src="https://s3.amazonaws.com/mvive-news-images/images-news/13-feb-2.jpg" alt="Zhukova jewelry"></a>
              <div class="media-body"> <a href="http://mvive.net/news/zhukova-jewelry-nova-kolekciya-love-is" class="catg_title">Zhukova jewelry: нова колекція "Love is"</a> </div>
            </div>
          </li>
          <li>
            <div class="media wow fadeInDown"> <a href="http://mvive.net/news/ostel-fw-2017-18-foto-novoi-kolekcii" class="media-left"><img src="https://s3.amazonaws.com/mvive-news-images/images-news/29-yanva-1.jpg" alt="OSTEL FW 2017/18"></a>
              <div class="media-body"> <a href="http://mvive.net/news/ostel-fw-2017-18-foto-novoi-kolekcii" class="catg_title">OSTEL FW 2017/18: фото нової колекції</a> </div>
            </div>
          </li>
        </ul>
      </div>
      <div class="single_sidebar wow fadeInDown">
        <h2><span>Краса та здоров'я з MonReal</span></h2>
        <a href="http://monreal.lviv.ua/" target="_blank" rel="nofollow" ><%= image_tag "monreal-banner.jpg", class: "ria-img-j" %></a>
      </div>
      <div class="single_sidebar">
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active"><a href="#video" aria-controls="profile" role="tab" data-toggle="tab">M'Vive TV</a></li>
          <li role="presentation"><a href="#category" aria-controls="home" role="tab" data-toggle="tab">Категорії</a></li>
          <li role="presentation"><a href="#comments" aria-controls="messages" role="tab" data-toggle="tab">Голосування</a></li>
        </ul>
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="video">
            <div class="vide_area">
              <iframe width="100%" height="250" src="https://www.youtube.com/embed/1mCEMF4Ceuk" frameborder="0" allowfullscreen></iframe>
            </div>
          </div>
          <div role="tabpanel" class="tab-pane" id="category">
            <ul>
              <li class="cat-item"><a href="#">Світське життя</a></li>
              <li class="cat-item"><a href="#">Fashion</a></li>
              <li class="cat-item"><a href="#">LifeStyle</a></li>
              <li class="cat-item"><a href="#">Краса</a></li>
              <li class="cat-item"><a href="#">MVive Fashion TV</a></li>
              <li class="cat-item"><a href="#">Покази моди</a></li>
            </ul>
          </div>
          <!--<div role="tabpanel" class="tab-pane" id="comments">
            <ul class="spost_nav">
              <li>
                <div class="media wow fadeInDown"> <a href="pages/single_page.html" class="media-left"> <%= image_tag "post_img1.jpg" %> </a>
                  <div class="media-body"> <a href="pages/single_page.html" class="catg_title"> Aliquam malesuada diam eget turpis varius 1</a> </div>
                </div>
              </li>
              <li>
                <div class="media wow fadeInDown"> <a href="pages/single_page.html" class="media-left"> <%= image_tag "post_img2.jpg" %> </a>
                  <div class="media-body"> <a href="pages/single_page.html" class="catg_title"> Aliquam malesuada diam eget turpis varius 2</a> </div>
                </div>
              </li>
              <li>
                <div class="media wow fadeInDown"> <a href="pages/single_page.html" class="media-left"> <%= image_tag "post_img1.jpg" %> </a>
                  <div class="media-body"> <a href="pages/single_page.html" class="catg_title"> Aliquam malesuada diam eget turpis varius 3</a> </div>
                </div>
              </li>
              <li>
                <div class="media wow fadeInDown"> <a href="pages/single_page.html" class="media-left"> <%= image_tag "post_img2.jpg" %> </a>
                  <div class="media-body"> <a href="pages/single_page.html" class="catg_title"> Aliquam malesuada diam eget turpis varius 4</a> </div>
                </div>
              </li>
            </ul>
          </div>-->
        </div>
      </div>
      <div class="single_sidebar wow fadeInDown">
        <h2><span>Блог</span></h2>
        <a class="sideAdd" href="http://mvive.net/blog_khrystyna_kolyada/military"><%= image_tag "blog-photo1.jpg" %></a>
        <div style="padding-left: 160px; text-align: center">
          <p style="padding-top: 60px;font-size: 17px;">Христина Коляда</p>
          <p style="font-size: 15px; font-weight: bold">Мілітарі</p>
          <p style="font-size: 14px; font-style: italic">«Це стиль, у якому використовують деталі та елементи військового одягу...»</p>
        </div>
      </div>
      <div class="single_sidebar wow fadeInDown">
        <h2><span>Facebook</span></h2>
        <div class="fb-page" data-href="https://www.facebook.com/mvivenet/" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/mvivenet/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/mvivenet/">M&#039;Vive - Мода 2017/18</a></blockquote></div>
      </div>
      <div class="single_sidebar wow fadeInDown">
        <h2><span>Вибір редакції</span></h2>
        <ul>
          <li><a href="http://lvivfashionweek.com/" rel="nofollow">Lviv Fashion Week</a></li>
          <li><a href="http://mvive.net/blog_khrystyna_kolyada">MVive Блоги</a></li>
          <li><a href="http://ria-ukraine.com/" rel="nofollow">РІА-Україна</a></li>
        </ul>
      </div>
    </aside>
  </div>
</div>

app/views/shared/_content_fashionshow.html.erb
<div class="row">
  <div class="col-lg-8 col-md-8 col-sm-8">
    <div class="left_content">

      <div class="single_moda_content">
        <h2><span>Покази моди</span></h2>
        <div class="single_moda_content_left">
          <ul class="moda_catgnav">
            <li>
              <% @fashionshow.each do |fashionshow| %>
                  <figure class="bsbig_fig  wow fadeInDown"> <a class="featured_img" href="<%= fashionshow_path(fashionshow) %>"> <img src="<%= fashionshow.image %>"><span class="overlay2"></span> </a>
                    <figcaption> <h1 style="font-size: 23px"><a href="<%= fashionshow_path(fashionshow) %>"><%= fashionshow.name %></a></h1> </figcaption>
                    <p style="border-bottom: 1px solid #000000;"><%= fashionshow.short %></p>
                  </figure>
              <% end %>
            </li>
          </ul>
        </div>

      </div>
    </div>
  </div>
  <div class="col-lg-4 col-md-4 col-sm-4">
    <aside class="right_content">
      <div class="single_sidebar">
        <h2><span>Популярні новини</span></h2>
        <ul class="spost_nav">
          <li>
            <div class="media wow fadeInDown"> <a href="http://mvive.net/news/anna_october_resort_2017_leto_blizko" class="media-left"><img src="https://s3.amazonaws.com/mvive-news-images/images-news/27-noya-2.jpeg" alt="Anna October Resort 2017"></a>
              <div class="media-body"> <a href="http://mvive.net/news/anna_october_resort_2017_leto_blizko" class="catg_title">Anna October Resort 2017: лето близко</a> </div>
            </div>
          </li>
          <li>
            <div class="media wow fadeInDown"> <a href="http://mvive.net/news/grammy-2017-epatagni-naryadu-ceremonii" class="media-left"><img src="https://s3.amazonaws.com/mvive-news-images/images-news/13-feb2-1.jpg" alt="Grammy 2017"></a>
              <div class="media-body"> <a href="http://mvive.net/news/grammy-2017-epatagni-naryadu-ceremonii" class="catg_title">Grammy 2017: епатажні наряди церемонії</a> </div>
            </div>
          </li>
          <li>
            <div class="media wow fadeInDown"> <a href="http://mvive.net/news/zhukova-jewelry-nova-kolekciya-love-is" class="media-left"><img src="https://s3.amazonaws.com/mvive-news-images/images-news/13-feb-2.jpg" alt="Zhukova jewelry"></a>
              <div class="media-body"> <a href="http://mvive.net/news/zhukova-jewelry-nova-kolekciya-love-is" class="catg_title">Zhukova jewelry: нова колекція "Love is"</a> </div>
            </div>
          </li>
          <li>
            <div class="media wow fadeInDown"> <a href="http://mvive.net/news/ostel-fw-2017-18-foto-novoi-kolekcii" class="media-left"><img src="https://s3.amazonaws.com/mvive-news-images/images-news/29-yanva-1.jpg" alt="OSTEL FW 2017/18"></a>
              <div class="media-body"> <a href="http://mvive.net/news/ostel-fw-2017-18-foto-novoi-kolekcii" class="catg_title">OSTEL FW 2017/18: фото нової колекції</a> </div>
            </div>
          </li>
        </ul>
      </div>
      <div class="single_sidebar">
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active"><a href="#video" aria-controls="profile" role="tab" data-toggle="tab">M'Vive TV</a></li>
          <li role="presentation"><a href="#category" aria-controls="home" role="tab" data-toggle="tab">Категорії</a></li>
          <li role="presentation"><a href="#comments" aria-controls="messages" role="tab" data-toggle="tab">Голосування</a></li>
        </ul>
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="video">
            <div class="vide_area">
              <iframe width="100%" height="250" src="https://www.youtube.com/embed/1mCEMF4Ceuk" frameborder="0" allowfullscreen></iframe>
            </div>
          </div>
          <div role="tabpanel" class="tab-pane" id="category">
            <ul>
              <li class="cat-item"><a href="#">Світське життя</a></li>
              <li class="cat-item"><a href="#">Fashion</a></li>
              <li class="cat-item"><a href="#">LifeStyle</a></li>
              <li class="cat-item"><a href="#">Краса</a></li>
              <li class="cat-item"><a href="#">MVive Fashion TV</a></li>
              <li class="cat-item"><a href="#">Покази моди</a></li>
            </ul>
          </div>
          <!--<div role="tabpanel" class="tab-pane" id="comments">
            <ul class="spost_nav">
              <li>
                <div class="media wow fadeInDown"> <a href="pages/single_page.html" class="media-left"> <%= image_tag "post_img1.jpg" %> </a>
                  <div class="media-body"> <a href="pages/single_page.html" class="catg_title"> Aliquam malesuada diam eget turpis varius 1</a> </div>
                </div>
              </li>
              <li>
                <div class="media wow fadeInDown"> <a href="pages/single_page.html" class="media-left"> <%= image_tag "post_img2.jpg" %> </a>
                  <div class="media-body"> <a href="pages/single_page.html" class="catg_title"> Aliquam malesuada diam eget turpis varius 2</a> </div>
                </div>
              </li>
              <li>
                <div class="media wow fadeInDown"> <a href="pages/single_page.html" class="media-left"> <%= image_tag "post_img1.jpg" %> </a>
                  <div class="media-body"> <a href="pages/single_page.html" class="catg_title"> Aliquam malesuada diam eget turpis varius 3</a> </div>
                </div>
              </li>
              <li>
                <div class="media wow fadeInDown"> <a href="pages/single_page.html" class="media-left"> <%= image_tag "post_img2.jpg" %> </a>
                  <div class="media-body"> <a href="pages/single_page.html" class="catg_title"> Aliquam malesuada diam eget turpis varius 4</a> </div>
                </div>
              </li>
            </ul>
          </div>-->
        </div>
      </div>
      <div class="single_sidebar wow fadeInDown">
        <h2><span>Блог</span></h2>
        <a class="sideAdd" href="http://mvive.net/blog_khrystyna_kolyada/military"><%= image_tag "blog-photo1.jpg" %></a>
        <div style="padding-left: 160px; text-align: center">
          <p style="padding-top: 60px;font-size: 17px;">Христина Коляда</p>
          <p style="font-size: 15px; font-weight: bold">Мілітарі</p>
          <p style="font-size: 14px; font-style: italic">«Це стиль, у якому використовують деталі та елементи військового одягу...»</p>
        </div>
      </div>
      <div class="single_sidebar wow fadeInDown">
        <h2><span>Facebook</span></h2>
        <div class="fb-page" data-href="https://www.facebook.com/mvivenet/" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/mvivenet/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/mvivenet/">M&#039;Vive - Мода 2017/18</a></blockquote></div>
      </div>
      <div class="single_sidebar wow fadeInDown">
        <h2><span>MVive рекомендує</span></h2>
        <ul>
          <li><a href="http://lvivfashionweek.com/" rel="nofollow">Lviv Fashion Week</a></li>
          <li><a href="#">MVive Blogs</a></li>
          <li><a href="https://vk.com/wonderlandstudio444">Wonderland Studio and Production</a></li>
        </ul>
      </div>
    </aside>
  </div>
</div>

app/views/shared/_sliders_mainpage.html.erb
<div class="row">
  <div class="col-lg-8 col-md-8 col-sm-8">
    <div class="slick_slider">
      <div class="single_iteam"> <a href="http://mvive.net/peopleandparty/kavalier-beach-club-art-season-2017-vidkritya-sezony"><img src="https://s3.amazonaws.com/mvive-news-images/images-people-and-party/kavalier-bp-1.jpg" alt="Kavalier Вeach Сlub Art season 2017: відкриття сезону"></a>
        <div class="slider_article">
          <h2><a class="slider_tittle" href="http://mvive.net/peopleandparty/kavalier-beach-club-art-season-2017-vidkritya-sezony">Kavalier Вeach Сlub Art season 2017: відкриття сезону</a></h2>
          <p>Понад 1000 гостів Львова та столиці, покази українських дизайнерів і виступи Jean Gritsfeldt, Alekseev та Даша Астафьева.</p>
        </div>
      </div>
      <div class="single_iteam"> <a href="http://mvive.net/mvive_tv/videoreportag-lviv-fashion-week-aw17-kateryna-karol"> <img src="https://s3.amazonaws.com/mvive-news-images/images-mvivetv/lwfaw17-f-tv.jpg" alt="Відеорепортаж Lviv Fashion Week AW17: Kateryna Karol"></a>
        <div class="slider_article">
          <h2><a class="slider_tittle" href="http://mvive.net/mvive_tv/videoreportag-lviv-fashion-week-aw17-kateryna-karol">Lviv Fashion Week AW17: Kateryna Karol</a></h2>
          <p>Відеорепортаж з показу нової колекції Катерини Кароль, який пройшов в рамках Lviv Fashion Week AW17 у Львівярні.</p>
        </div>
      </div>
      <div class="single_iteam"> <a href="http://mvive.net/news/miss-lviv-2017-kastyng"><img src="https://s3.amazonaws.com/mvive-news-images/images-news/misslviv-cast-8.jpg" alt="Міс Львів 2017"></a>
        <div class="slider_article">
          <h2><a class="slider_tittle" href="http://mvive.net/news/miss-lviv-2017-kastyng">Міс Львів 2017: Кастинг</a></h2>
          <p>30 березня 2017 року відбувся кастинг конкурсу краси “Міс Львів 2017” . За право отримати головну корону міста та право володіти титулом найкрасивішої львів”янки року прийшли позмагатись не тільки красиві...</p>
        </div>
      </div>
      <div class="single_iteam"> <a href="http://mvive.net/peopleandparty/dilovyi-forum-2017-citadel-inn-afterparty"><img src="https://s3.amazonaws.com/mvive-news-images/images-people-and-party/dil-forum-1.jpg" alt="Діловий Форум 2017: Citadel Inn Afterparty"></a>
        <div class="slider_article">
          <h2><a class="slider_tittle" href="http://mvive.net/peopleandparty/dilovyi-forum-2017-citadel-inn-afterparty">Діловий Форум 2017: Citadel Inn Afterparty</a></h2>
          <p>Як відпочивали багаті та успішні бізнесмени після Ділового форуму на Afterparty у Готелі Citadel Inn</p>
        </div>
      </div>
      <div class="single_iteam"> <a href="http://mvive.net/mvive_tv/lviv-fashion-week-aw17-day2-lesia-semi-balossa-bob-basset"><img src="https://s3.amazonaws.com/mvive-news-images/images-mvivetv/Wimeo_cower_2.jpg" alt="Lviv Fashion Week AW17 Day 2: Lesia Semi, Balossa/Bob Basset"></a>
        <div class="slider_article">
          <h2><a class="slider_tittle" href="http://mvive.net/mvive_tv/lviv-fashion-week-aw17-day2-lesia-semi-balossa-bob-basset">Lviv Fashion Week AW17 Day 2: Lesia Semi, Balossa/Bob Basset</a></h2>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-4 col-md-4 col-sm-4">
    <div class="latest_post">
      <h2><span>Останні оновлення</span></h2>
      <div class="latest_post_container">

        <ul class="latest_postnav">
          <li>
            <% @news.each do |news| %>
            <div class="media"> <a href="<%= news_path(news) %>" class="media-left"><img src="<%= news.image %>"></a>
              <div class="media-body"> <a href="<%= news_path(news) %>" class="catg_title"><%= news.name %></a> </div>
            </div>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>